version: '3.8'
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27018:27017'

  backend:
    container_name: backend
    build:
      context: .
    command: bash -c "npm run dev"
    volumes:
      - ./src:/app/src
    ports:
      - 4000:4000
    env_file:
      - .env.development
    depends_on:
      - mongo

volumes:
  mongo_data:
